# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 01:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body_part', models.CharField(choices=[('arms', 'Arms'), ('legs', 'Legs'), ('chest', 'Chest'), ('back', 'Back'), ('core', 'Core')], max_length=50)),
                ('variation', models.CharField(max_length=100)),
                ('modality', models.CharField(choices=[('barbell', 'Barbell'), ('kettlebell', 'Kettlebell'), ('dumbbell', 'Dumbbell'), ('body-weight', 'Body Weight'), ('machine', 'Machine'), ('cable', 'Cable'), ('smith', 'Smith'), ('band', 'Band')], help_text='Method of exercise', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep_style', models.CharField(choices=[('str', 'Strength'), ('hypertrophy', 'Hypertrophy'), ('power', 'Power'), ('endurance', 'Endurance')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('intensity', models.IntegerField()),
                ('load', models.IntegerField(help_text='Weight in pounds')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.Exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.Workout')),
            ],
        ),
    ]
