# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='variation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
