# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_auto_20170622_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutset',
            name='reps',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
